language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install .
  - pip install --upgrade -r requirements-dev.txt

script:
  - flake8
  - pytest

after_success:
  - codecov

notifications:
  email: false